### ISSUE TITLE
Search not working on new content, and not displaying right on mobile

### ISSUE THREAD

**Issue by ngawangtrinley** [gristlabs/mkdocs-windmill#1]
I'm using your theme to build a documentation site on Tibetan NLP in Tibetan. I've opted to download the theme folder from github, but somehow the search doesn't build properly and the search bar doesn't scale properly on my mobile. My project is [here](http://arapatsa.com).

![bug](https://cloud.githubusercontent.com/assets/17675331/26530097/ad50fc6e-4400-11e7-9457-204a94dcf29a.PNG)

Thanks a lot for building this theme! It's going to be great.

**Comment by dsagal** [comment]
Apologies! This is brand new - mobile indeed doesn't work yet. I started on
it, hope to have it later this week.

**Comment by ngawangtrinley** [comment]
Great! I'll keep an eye on the project. It's going to be useful for many people

**Comment by dsagal** [comment]
I made a lot of fixes for mobile, and published a new version. Please take a look! There is an example here: https://gristlabs.github.io/mkdocs-windmill/. Let me know what issues you find.

**Comment by ngawangtrinley** [comment]
It's looking great now, and the search works perfect. One thing when viewing on computer screens though, limiting the width of the text would make reading easier. Cheers!

**Comment by dsagal** [comment]
Excellent, I'll close this issue then.

Good idea for limiting the width: I added a limit of 700px (as medium.com does) on master. You can override it by using `extra.css` and setting `.wm-page-content { width: <other>; }` there.
