### ISSUE TITLE
Provide example for extra customisation options

### ISSUE THREAD

**Issue by rei-vilo** [gristlabs/mkdocs-windmill#10]
After reading the [Customization](https://gristlabs.github.io/mkdocs-windmill/#customization/) and the [Customizing a Theme](http://www.mkdocs.org/user-guide/styling-your-docs/#customizing-a-theme), I can't figure out how to define the `extra` parameters on the `mkdocs.yml`.

What I've tried so far:

```
theme: windmill

extra:
    - extra.logo: 'img/Logo-128.png'
```

```
theme: windmill

extra:
extra.logo: 'img/Logo-128.png'
```

The error messages are

> The configuration is invalid. The expected type was a key value mapping (a python dict) but we got an object of type: <type 'NoneType'>

> The configuration is invalid. The expected type was a key value mapping (a python dict) but we got an object of type: <type 'NoneType'>

Could you please provide an example for the `extra` customisation options? Thank you!

**Comment by dsagal** [comment]
Try:
```
extra:
  logo: 'img/Logo-128.png'
```
I agree there should be an example to the docs.

**Comment by rei-vilo** [comment]
It worked fine. Thank you very much!
