### ISSUE TITLE
Search results not appearing

### ISSUE THREAD

**Issue by claudiopi** [gristlabs/mkdocs-windmill#13]
Hi,

I followed the install instructions and I am using the development server (mkdocs serve) without extra configuration besides your theme: 

site_name: My Site
theme: windmill

When I do I search I get the default theme style without highlighting. But if I click twice on the search box then the highlight appears. Also when I click on SEE ALL RESULTS http://localhost:8000/#search.html?q=test I get a 404 for that page. 

Do I need to setup anything else for the search to work correctly ?

Thanks,
Claudio.

**Comment by noraj1337** [comment]
This theme works until mkdocs 0.16.3 but not 0.17.x. It need to be updated.
See http://www.mkdocs.org/about/release-notes/#version-0170-2017-10-19, https://github.com/mkdocs/mkdocs/issues/1363

**Comment by noraj1337** [comment]
See https://github.com/mkdocs/mkdocs/issues/1316

**Comment by dsagal** [comment]
This is now fixed.
