### ISSUE TITLE
mkdocs complains about a missing configuration file

### ISSUE THREAD

**Issue by osg-cat** [gristlabs/mkdocs-windmill#14]
I am using MkDocs with the Windmill theme for a new site. I have a Docker container running a development server during development, then I use Travis CI from GitHub to build the actual site into GitHub Pages. In both places, which use the most recent version of mkdocs-windmill available to pip, I get a warning:

WARNING -  The theme 'windmill' does not appear to have a configuration file. Please upgrade to a current version of the theme. 

Looking at the MkDocs source code, it appears to be looking for a `mkdocs_theme.yml` file. Could you provide one to prevent the warning?

**Comment by noraj1337** [comment]
This theme works until mkdocs 0.16.3 but not 0.17.x. It need to be updated.
See http://www.mkdocs.org/about/release-notes/#version-0170-2017-10-19, https://github.com/mkdocs/mkdocs/issues/1363

**Comment by dsagal** [comment]
This is now fixed.
