### ISSUE TITLE
Add bootstrap.min.css.map to css directory

### ISSUE THREAD

**Issue by osg-cat** [gristlabs/mkdocs-windmill#15]
Please consider adding the `bootstrap.min.css.map` file from the standard Bootstrap distribution to the theme CSS directory. It seems to be used when examining rendered pages in developer mode.

**Comment by ysagal** [comment]
Are you just trying to get rid of the 404? We could remove the reference to it from the css file so that the browser doesn't try to fetch it. That way it wouldn't bloat the theme.

**Comment by osg-cat** [comment]
The *.map files are “CSS source maps” and seem to be used by some browsers when in development mode. They are mentioned on the [Bootstrap Getting started page](https://getbootstrap.com/docs/3.3/getting-started/) and elsewhere.

I’m not sure what your concern about bloat is. It is a single half-megabyte file, and at least in my observations (macOS, Safari) is only downloaded by the browser when activating development mode for a page. I see little downside to adding this file.

**Comment by ysagal** [comment]
My question is whether you'd like the css map included to help you with development (or for some other reasons) or if you're just trying to get rid of the 404 error when the browser attempts to fetch it. I don't have concerns about adding it to the theme if it's useful, but looking at some other mkdocs themes I see that they generally don't include the map for bootstrap.

**Comment by osg-cat** [comment]
Ah, I see. I haven’t done a lot of with/without comparisons — I just added the source map file on my development instance and mostly used it there. My sense is that is helpful when trying to dig into the particulars of (in my case) the CSS and where particular rules come from in the original, un-compiled and minified Bootstrap source. Admittedly a minor use case.

**Comment by dsagal** [comment]
I added .map files.
