### ISSUE TITLE
Does not support ie

### ISSUE THREAD

**Issue by Jacobbrent15** [gristlabs/mkdocs-windmill#3]
Hi, I recently installed the windmill package as my theme. On chrome it works just fine although a pointer on how to decrease the width of the page so that the text and everything doesn't seem so small would be helpful. But on ie the first page doesn't open up the content. And then when you click on anything in navigation after going to the page you clicked the navigation bar disappears completely. Any ideas on how to fix?
Thanks.

**Comment by dsagal** [comment]
Thank you for the report. I added a fix to get it to work on IE, and published a new version (v0.1.2). Could you please confirm that it works for you now, and close this issue if so?

**Comment by dsagal** [comment]
The fix for IE is in, so closing the issue.
