### ISSUE TITLE
Error with search option

### ISSUE THREAD

**Issue by y2kkarthik** [gristlabs/mkdocs-windmill#31]
I am using windmill theme for mkdocs to generate static webpages. Good news is everything works charm as expected however I have an issue with search option.

When I search for any resources the url is changed to http://#.
Please notice a dot(.) between domain and key which is causing the problem. When I checked search.html, I could see key is present without dot(.) which is correct

Wondering where an extra dot(.) is getting appended during the search. Any leads on this issue would be highly appreciated

PS: I do not have any fancy configurations in mkdocs.yaml and I have kept very basic

Regards,
Karthik

**Comment by y2kkarthik** [comment]
Fixed the issue be reverting mkdocs version to 0.17

**Comment by morblom** [comment]
That isn't really a fix though, more of a workaround. The underlying issue should be fixed.

**Comment by dsagal** [comment]
I just pushed a fix that fixes the search URLs for mkdocs 1.0.
