### ISSUE TITLE
index.md problem

### ISSUE THREAD

**Issue by shadialtarsha** [gristlabs/mkdocs-windmill#32]
Hello guys, nice theme btw
I am trying to build the menu. The problem is the menu item that points to the index.md file generated without anchor tag, so the menu item that is associated with it, is not clickable.
My mkdocs.yml:
```
site_name: some site
theme: 'windmill'
nav: 
  - Introduction: 'index.md'
  - Purpose of the system design document : 'purpose of the system design document.md'
  - General overview and design guidelines/approach: 
    - General overview : 'general overview.md'
    - Assumptions/Constraints: 
      - Assumptions: 'assumptions.md'
      - Constraints: 'constraints.md'
  - Desing considerations: 
      - Goals: 'goals.md'  
      - Dependencies: 'dependencies.md'  
  - Overall system architecture:
      - Functional architecture:
        - UAE pass mobile app : 'uae pass mobile app.md'
        - UAE pass self-service portal: 'uae pass self-service portal.md'
      - Infrastructure architecture: 'infrastructure architecture.md'  
      - Network architecture : 'network architecture.md'
      - Security architecture : 'security architecture.md'
  - Operational scenarios: 
      - User enrolments : 'user enrolments.md'
      - Auth : 'auth.md'
      - Change email/mobile : 'change email-mobile.md'
      - User profile management: 'user profile management.md'
      - Notifications: 'notifications.md'
      - Google Drive and Dropbox integration : 'google drive and dropbox integration.md'
  - Databases design: 'database design.md'
  - Interfaces UX/UI: 'interfaces.md'
  - Acronyms and Abbreviations: 'acronyms and abbreviations.md'  
```
Every other menu or menu item works correctly except the "Introduciton"

**Comment by dsagal** [comment]
Which version of mkdocs are you using? This theme has not been updated to work properly with mkdocs 1.0. Assuming you are using 0.17, try replacing `nav` with `pages`.

**Comment by shadialtarsha** [comment]
Yeah i am using the latest version of mkdocs. ok thank you

**Comment by TBRC-JimK** [comment]
Hi @dsagal, replacing `nav` with `pages` had no effect on my problem, but manually adding @palto42 fix to #30 fixed it. (I had a similar problem with links to sub directory pages not working.)

**Comment by shadialtarsha** [comment]
any work around I can do to make it work? I tried to edit the source file but the changing have never reflected on my project, and I am by any mean no nothing in Python or the template engine that has been used with this module

**Comment by shadialtarsha** [comment]
Just added (use_directory_urls: false) to my mkdocs.yml fixed it. don't know why.

**Comment by dsagal** [comment]
I added `use_directory_urls: false` instruction to the README, which addresses a few navigation issues.
