### ISSUE TITLE
External links in menu bar doesn’t work!:help-wanted

### ISSUE THREAD

**Issue by kbhutiya** [gristlabs/mkdocs-windmill#34]
Hi,
I am trying to have a menu links in the sidebar where i can just given an url to html file! 
I know it can be done with 
nav:
        - Test: "http://example.com" 

But i am not using nav at all!
I have 

theme:
  name: null
  custom_dir: theme
  search_index_only: true
  include_search_page: true

And it takes the folder structure automatically! if i will use nav, it override my current folder structure!

**Comment by dsagal** [comment]
I don't think mkdocs allows mixing the auto-generated nav with customizations (see [here](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation)). So to get what you'd like, you'll need to write out the full `nav` configuration.
