### ISSUE TITLE
Content Frame Size

### ISSUE THREAD

**Issue by pcasalinho** [gristlabs/mkdocs-windmill#39]
This is not an issue but, how can I change the content frame size to use the entire screen.
I'm using Full HD (10920x1080) and there's too much empty screen.

The Ivory Theme, for example uses the entire frame to display the content.

I love the Windmill Theme!

**Comment by dsagal** [comment]
I am guessing what bothers you is a setting on `.wm-page-content` style, of `max-width: 700px`. 

You can override with
```
extra_css:
  - css/your-overrides.css
```
And add to `css/your-overrides.css` (under your `docs_dir`)
```
.wm-page-content {
  max-width: none;  /* or perhaps 70% or something else */
}
```

**Comment by pcasalinho** [comment]
That's Exactly it! Thanks a lot!
