### ISSUE TITLE
TOC navigation glitch

### ISSUE THREAD

**Issue by ngawangtrinley** [gristlabs/mkdocs-windmill#4]
The TOC navigation has a small glitch: the title that is selected hides behind the top banner. For instance when I select the page [Workflow](https://buddhistdigitalresourcecenter.github.io/digitization-guidelines/#workflow/workflow-en/#digitization-workflow), the title is displayed properly.
![image](https://user-images.githubusercontent.com/17675331/28616548-b750a45a-722f-11e7-9e89-fc8eb1b75295.png)
But when I click on [Digitization Workflow](https://buddhistdigitalresourcecenter.github.io/digitization-guidelines/#workflow/workflow-en/#digitization-workflow), most of the title disappears behind the banner.
![image](https://user-images.githubusercontent.com/17675331/28616886-f4a9aca6-7230-11e7-9142-7831a688217f.png)

Is that a problem you experience too? Is there something to do about it?

**Comment by dsagal** [comment]
Let me know if you can test the behavior in the pull request please.

**Comment by dsagal** [comment]
Haven't heard back, so will assume the fix is sufficient.
