### ISSUE TITLE
Previous/Next overlap with contents when using master

### ISSUE THREAD

**Issue by mike-schiller** [gristlabs/mkdocs-windmill#9]
This behavior seems to have been introduced since v0.1.2

**Comment by dsagal** [comment]
Thanks for the report! I noticed that while addressing another issue and have a fix. Do you mind trying branch `file_urls` to see if it's good there?

**Comment by mike-schiller** [comment]
unfortunately, I see the same issue with that branch

**Comment by dsagal** [comment]
Thanks for checking. Could you share which OS/browser you are using? Is the problem with the links on top or on the bottom, or both? If you could attach a screenshot, that would be very helpful too.

**Comment by mike-schiller** [comment]
OS X & Chrome

**Comment by mike-schiller** [comment]
I tracked this down to the fact that many of the .md files I use start with a H2 (##) or no heading rather than an H1(##). I can certainly change my docs to start with H1 - especially because H1 is styled better in Windmill than in the previous theme and in the markdown editor I use.

That said, I'm not sure what proper behavior is. Should starting with H2 or no heading be supported?

**Comment by dsagal** [comment]
Yeah, I think it should be supported. The problem is my workaround for #4 , but I think it can be done in a better way. I'll try it.

**Comment by dsagal** [comment]
This is now fixed.
